file_format: "1"
id: keyb
name: Keyb
type: shield
url: https://github.com/WafflesXD/zmk-config-keyb
requires:
  - xiao_ble
features:
  - keys
  - display
  - studio
siblings:
  - keyb_left
  - keyb_right
